### ISSUE TITLE
FEAT: реализация страницы аутентификации

### ISSUE THREAD

**Issue by NikitaNpl** [JudexMars/DB2D#18]
# Описание

Необходимо реализовать формы аутентификации по макетам: https://www.figma.com/file/j51Ww1Id26JpYrWlGq2I3P/DB2D?type=design&node-id=9-91&mode=design&t=xHtC3x7KWusLOn30-0

# Сценарии проверки

## Сценарий 1 - успешная регистрации

1. Зайти на страницу регистрации
2. Корректно заполнить все поля (в соответствии с подсказами на форме)
3. Нажать на кнопку "Зарегистрироваться"

### Ожидаемый результат

Пользовать успешно зарегистрируется

## Сценарий 2 - ошибка валидации на форме регистрации

1. Зайти на страницу регистрации
3. Нажать на кнопку "Зарегистрироваться"

### Ожидаемый результат

Будет ошибка валидации полей формы

## Сценарий 3 - успешная авторизации

1. Зайти на страницу авторизации
2. Корректно заполнить все поля (в соответствии с подсказами на форме)
3. Нажать на кнопку "Войти"

### Ожидаемый результат

Пользовать успешно авторизуется

## Сценарий 4 - ошибка валидации на форме авторизации

1. Зайти на страницу авторизации
3. Нажать на кнопку "Войти"

### Ожидаемый результат

Будет ошибка валидации полей формы

# Реализация сценариев

- [x] Сценарий 1 - успешная регистрации
- [x] Сценарий 2 - ошибка валидации на форме регистрации
- [x] Сценарий 3 - успешная авторизации
- [x] Сценарий 4 - ошибка валидации на форме авторизации

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by NikitaNpl** [comment]
Необходимо:

- [ ] добавить библиотеку для управления формами (для упрощенной валидации и хранения данных формы);
- [ ] добавить библиотеку для уведомлений в приложении;
- [ ] временно перевести хранение данных о пользователе в sessionStorage

**Comment by palyanaff** [comment]
Все сценарии отрабатывают
