### ISSUE TITLE
FEAT: Бэкенд-реализация многоязычной поддержки

### ISSUE THREAD

**Issue by JudexMars** [JudexMars/DB2D#19]
# Описание

- реализовать поддержку различных языков для текста ошибок (русский, английский)
- реализовать возможность настройки аккаунта пользователя для выбора языка интерфейса

# Сценарии проверки

- Выполнять через Postman или Swagger
Swagger URL: http://localhost:8080/swagger-ui/index.html#/

## Сценарий 1 - Успешная смена языка

1. Отправить по адресу localhost:8080/auth/signup POST-запрос с телом:
```
{
    "email":"john@yahoo.com",
    "firstname":"John",
    "lastname":"Smith",
    "password":"12345",
    "confirmPassword":"12345"
}
```

2. Добавить полученный access_token в Authorization Header (в Postman Authorization -> Type 'Bearer Token' -> Token, в Swagger нажать на кнопку Authorize)
3. Отправить GET-запрос по адресу localhost:8080/account/{id}/settings (где id - это id пользователя из предыдущего шага)
4. Отправить PUT-запрос по адресу localhost:8080/account/{id}/settings с телом:
```
{
  "accountId": {id},
  "language": "en"
}
```
5. Отправить PUT-запрос по адресу localhost:8080/account/{id}/settings с телом:
```
{
  "accountId": {id},
  "language": "ru"
}
```

## Ожидаемый результат

1. Ответ - 200 OK с телом:
```
{
    "accountId": 1,
    "accessToken":"токен 1",
    "refreshToken":"токен 2",
    "email": "john@yahoo.com"
}
```
3. Ответ - 200 ОК с телом:
```
{
  "accountId": {id},
  "language": "ru"
}
```
4. Ответ - 200 ОК с телом:
```
{
  "accountId": {id},
  "language": "en"
}
```
5. Ответ - 200 ОК с телом:
```
{
  "accountId": {id},
  "language": "ru"
}
```

## Неудачная смена языка

1. Использовать аккаунт и токен из предыдущего сценария либо выполнить все перечисленные в нем шаги повторно
2. Отправить PUT-запрос по адресу localhost:8080/account/{id}/settings с телом:
```
{
  "accountId": {id},
  "language": "pl"
}
```
3. Убрать токен из Authorization
4. Отправить PUT-запрос по адресу localhost:8080/account/{id}/settings с телом:
```
{
  "accountId": {id},
  "language": "ru"
}
```

## Ожидаемый результат

2. Ответ - 404 NOT FOUND с телом:
```
{
  "status": 404,
  "message": "Язык (pl) не удалось найти"
}
```
4. Ответ - 403 FORBIDDEN с телом:
```
{
  "status": 403,
  "message": "Доступ запрещен"
}
```

# Реализация сценариев

- [x]  Успешная смена языка
- [x] Неудачная смена языка

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by palyanaff** [comment]
Все сценарии отрабатывают
