### ISSUE TITLE
FEAT: бекенд часть для авторизации пользователей

### ISSUE THREAD

**Issue by NikitaNpl** [JudexMars/DB2D#2]
# Описание

- продумать структуру сущности "Пользователи" БД
- спроектировать базовое REST API
- написать документацию на сущность "Пользователи"

# Сценарии проверки

- Проверять сценарии через PostMan
- Запуск приложения из директории server/db2d:
`docker-compose up --build -d`
- Остановка приложения:
`docker-compose down -v`

## Сценарий 1 - "Успешная регистрация"

1. Отправить по адресу localhost:8080/auth/signup POST-запрос с телом:
```
{
    "username":"John",
    "email":"john@yahoo.com",
    "firstname":"John",
    "lastname":"Smith",
    "password":"12345",
    "confirm_password":"12345"
}
```

## Ожидаемый результат

Ответ - 200 OK с телом:
```
{
    "account_id": 1,
    "access_token":"некий токен 1",
    "refresh_token":"некий токен 2",
    "username": "john"
}
```

##  Сценарий 2 - "Успешная авторизация"

1. Повторить сценарий 1 "Успешная регистрация"
2. Отправить по адресу localhost:8080/auth/login POST-запрос с телом:
 ```
{
    "username":"John",
    "password":"12345"
}
```

## Ожидаемый результат

Ответ - 200 OK с телом:
```
{
    "account_id": 1,
    "access_token":"<токен 1>",
    "refresh_token":"<токен 2>",
    "username": "john"
}
```

##  Сценарий 3 - "Успешное обновление токена"

1. Повторить сценарий 1 "Успешная регистрация"
2. Отправить по адресу localhost:8080/auth/refresh POST-запрос с телом:
```
{
    "token":"<refresh_token из результата сценария №2>"
}
```

## Ожидаемый результат

Ответ - 200 OK с телом:
```
{
    "account_id": 1,
    "access_token":"<токен 1>",
    "refresh_token":"<токен 2>",
    "username": "john"
}
```
Оба полученных токена должны отличаться от тех, что были получены в первом шаге

## Сценарий 4 - "Неудачная регистрация"

1. Отправить по адресу localhost:8080/auth/signup POST-запрос с телом:
```
{
    "username":"John",
    "email":"john@yahoo.com",
    "firstname":"John",
    "lastname":"Smith",
    "password":"12345",
    "confirm_password":"123456789"
}
```

## Ожидаемый результат

Ответ - 400 Bad Request с телом:
```
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "Пароли не совпадают",
    "instance": "/auth/signup"
}
```

## Сценарий 5 - "Неудачная авторизация"

1. Повторить сценарий 1 "Успешная регистрация"
2. Отправить по адресу localhost:8080/auth/login POST-запрос с телом:
 ```
{
    "username":"John",
    "password":"123456789"
}
```

## Ожидаемый результат

Ответ - 401 Bad Credentials с телом:
```
{
    "type": "about:blank",
    "title": "Unauthorized",
    "status": 401,
    "detail": "Bad credentials",
    "instance": "/auth/login"
}
```

##  Сценарий 6 - "Неудачное обновление токена"

1. Повторить сценарий 1 "Успешная регистрация"
2. Отправить по адресу localhost:8080/auth/refresh POST-запрос с телом:
```
{
    "token":"<случайный набор символов>"
}
```

## Ожидаемый результат

В случае, если токен просто отсутствует в refresh-таблице
Ответ - 403 Forbidden с телом:
```
{
    "type": "about:blank",
    "title": "Forbidden",
    "status": 403,
    "detail": "Доступ запрещен: JWT is not valid",
    "instance": "/auth/refresh"
}
```
В противном случае, detail может содержать 1 из 4 возможных ошибок: 

- Malformed JWT (неправильный формат)
Пример: `Malformed protected header JSON: Unable to deserialize: Unexpected character ('�' (code 65533 / 0xfffd)): was expecting comma to separate Object entries\n at [Source: (InputStreamReader); line: 1, column: 14]`
- JWT expired (токен просрочен)
Пример: `JWT expired 506346447 milliseconds ago at 2024-02-24T23:36:38.000Z. Current time: 2024-03-01T20:15:44.447Z. Allowed clock skew: 0 milliseconds.`
- Unsupported JWT (например, токен не зашифрован) 
Пример: `Invalid Base64Url protected header: eyJhbаGciOiJIUzI1NiJ9`
- Signature exception (подпись не верифицирована)
Пример: `Invalid Base64Url JWS signature: pl7GUFhIvC3G_19Go-24qYlPjKAulDUNFортшотршщEgBc01SHSE`

# Реализация сценариев

- [x] Сценарий 1 - "Успешная регистрация"
- [x] Сценарий 2 - "Успешная авторизация"
- [x] Сценарий 3 - "Успешное обновление токена"
- [x] Сценарий 4 - "Неудачная регистрация"
- [x] Сценарий 5 - "Неудачная авторизация"
- [x] Сценарий 6 - "Неудачное обновление токена"

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by palyanaff** [comment]
Все сценарии проверены, ошибок нет
