### ISSUE TITLE
FEAT: реализация страницы "Мой профиль"

### ISSUE THREAD

**Issue by NikitaNpl** [JudexMars/DB2D#20]
# Описание

Необходимо реализовать форму редактирования профиля пользователя

# Сценарии проверки

## Сценарий 1 - Успешное редактирование основной информации

1. Изменить Имя
2. Изменить Фамилию
3. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Отсутствие ошибок на форме

## Сценарий 2 - Неудачное редактирование основной информации

1. Очистить поле Имени или Фамилии
2. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Ошибка отсутствия заполнения одного или нескольких полей

## Сценарий 3 - Успешное изменение пароля

1. Написать пароль отличный от текущего
2. Повторить пароль
4. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Появляется тост с текстом "Пароль успешно изменен"

## Сценарий 4 - Неудачное изменение пароля

1. Написать пароль отличный от текущего
2. Написать отличный пароль от введенного в п.1
4. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Появляется тост с текстом "Пароли не совпадают"

# Реализация сценариев

- [x] Сценарий 1 - Успешное редактирование основной информации
- [x] Сценарий 2 - Неудачное редактирование основной информации
- [x] Сценарий 3 - Успешное изменение пароля
- [x] Сценарий 4 - Неудачное изменение пароля

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by palyanaff** [comment]
Все сценарии отрабатывают
