### ISSUE TITLE
FEAT: Бэкенд-реализация редактирования пользователя

### ISSUE THREAD

**Issue by JudexMars** [JudexMars/DB2D#23]
# Описание

- реализовать редактирование пользователя (аккаунта) его владельцем либо администратором

# Сценарии проверки

Выполнять с помощью swagger

## Удачное редактирование аккаунта

1. Зарегистрировать новый аккаунт
2. С access-token'ом отправить по адресу localhost:8080/account/{id} PUT-запрос с телом:
```
{
    "firstname": "man",
    "lastname": "woman"
}
```
3. Отправить по адресу localhost:8080/account/{id}/password PUT-запрос с телом:
```
{
    "oldPassword": "<пароль при регистрации>",
    "newPassword": "<новый пароль>"
}
```
4. Войти в аккаунт с новым паролем по адресу localhost:8080/login (POST)

## Ожидаемый результат

2. Ответ - 200 ОК с телом:
```
{
    "firstname": "man",
    "lastname": "woman"
}
```
3. Ответ - 200 ОК с телом:
```
{
  "status": 200,
  "message": "Пароль успешно обновлен"
}
```
4. Удачный вход, получение новых токенов

# Реализация сценариев

- [x]  Удачное редактирование аккаунта

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by palyanaff** [comment]
Сценарий отрабатывает
