### ISSUE TITLE
FEAT: Реализация Toast уведомлений пользователя

### ISSUE THREAD

**Issue by commonPlaceC** [JudexMars/DB2D#28]
# Описание
Необходимо реализовать Toast уведомления пользователя, используя библиотеку react-toastify.
# Сценарии проверки

## Сценарий 1 - Успешная регистрация

1. Зайти на страницу регистрации
2. Корректно заполнить все поля (в соответствии с подсказами на форме)
3. Нажать на кнопку "Зарегистрироваться"

### Ожидаемый результат

Пользовать успешно зарегистрируется. Выведется toast уведомление об успешной регистрации

## Сценарий 2 - Ошибка валидации на форме регистрации

1. Зайти на страницу регистрации
2. Нажать на кнопку "Зарегистрироваться"

### Ожидаемый результат

Будет ошибка валидации полей формы

## Сценарий 3 - Отправка невалидных данных регистрации

1. Зайти на страницу регистрации
2. Корректно заполнить все поля
3. Внести случайные изменения в поле подтверждения пароля
4. Нажать на кнопку "Зарегистрироваться"

### Ожидаемый результат

Выведется toast уведомление об неудачной регистрации 

## Сценарий 4 - Успешная авторизация

1. Зайти на страницу авторизации
2. Корректно заполнить все поля (в соответствии с подсказами на форме)
3. Нажать на кнопку "Войти"

### Ожидаемый результат

Пользовать успешно авторизуется. Выведется toast уведомление об успешной регистрации

## Сценарий 5 - Ошибка валидации на форме авторизации

1. Зайти на страницу авторизации
2. Нажать на кнопку "Войти"

### Ожидаемый результат

Будет ошибка валидации полей формы

## Сценарий 6 - Отправка невалидных данных авторизации

1. Зайти на страницу авторизации
2. Корректно заполнитель поле логина и ввести неправильный пароль в поле пароля
3. Нажать на кнопку "Войти"

### Ожидаемый результат

Выведется toast уведомление об неудачной авторизации

## Сценарий 7 - Успешное редактирование основной информации

1. Изменить Имя
2. Изменить Фамилию
3. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Отсутствие ошибок на форме. Выведется toast уведомление об успешной авторизации

## Сценарий 8 - Неудачное редактирование основной информации

1. Очистить поле Имени и/или Фамилии
2. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Ошибка отсутствия заполнения одного или нескольких полей

## Сценарий 9  - Успешное изменение пароля

1. Написать пароль отличный от текущего
2. Повторить пароль
5. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Выведется toast уведомление об успешной смене пароля

## Сценарий 10 - Неудачное изменение пароля

1. Написать пароль отличный от текущего
2. Написать отличный пароль от введенного в п.1
4. Нажать на кнопку "Сохранить" 

### Ожидаемый результат

Выведется toast уведомление об ошибке смене пароля

# Реализация сценариев

- [x]  Сценарий 1 - Успешная регистрация
- [x]  Сценарий 2 - Ошибка валидации на форме регистрации
- [x]  Сценарий 3 - Отправка невалидных данных регистрации
- [x]  Сценарий 4 - Успешная авторизация
- [x]  Сценарий 5 - Ошибка валидации на форме авторизации
- [x]  Сценарий 6 - Отправка невалидных данных авторизации
- [x]  Сценарий 7 -  Успешное редактирование основной информации
- [x]  Сценарий 8 - Неудачное редактирование основной информации
- [x]  Сценарий 9 - Успешное изменение пароля
- [x]  Сценарий 10 - Неудачное изменение пароля

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by commonPlaceC** [comment]
@palyanaff

**Comment by palyanaff** [comment]
Все сценарии отрабатывают
