### ISSUE TITLE
FEAT: настроить заготовку для web-части приложения

### ISSUE THREAD

**Issue by NikitaNpl** [JudexMars/DB2D#9]
# Описание

Необходимо выбрать версию react-приложения
Определиться с начальными библиотеками необходимыми при разработке
Настроить линтер

# Сценарии проверки

Перед проверкой необходимо установить nodejs: https://nodejs.org/en/download

## Сценарий 1  - "Успешный запуск клиента"
1. Перейти в директорию: `cd ./client`
2. Установить пакеты node: `npm install`
3. После установки пакетов запустить клиент: `npm run start`
4. После окончания запуска проекта, перейти на `http://localhost:3000` в каждом из браузеров: Chrome, Safari, Firefox, Edge и убедиться, что отображается базовая страница React
5. Проверить, что запуск прошел успешно, в консоли должно быть указано _webpack compiled successfully_
# Реализация сценариев

- [x]  Сценарий 1 - "Успешный запуск клиента"

# Definition of Done (готовность к сдаче)

- [x]  Проверены все сценарии
- [x]  Ветка содержит актуальную версию master
- [x]  Приложение собирается и запускается без ошибок и предупреждений
- [x]  Обновлена документация
- [x]  Описание MR содержит ссылку на карточку задачи, чеклисты Definition of Done и Сценарии проверки
- [x]  MR имеет ответственного (assignee)
- [x]  Карточка задачи перенесена в дорожку “REVIEW“
- [x]  Ответственный добавлен в список участников карточки

**Comment by commonPlaceC** [comment]
@palyanaff Проверь сценарий проверки 1.

**Comment by palyanaff** [comment]
Сценарий отрабатывает
